# export OPENAI_API_KEY="sk-..."
python main.py train system_prompts synthetic 16
python main.py test system_prompts synthetic 15
python main.py test system_prompts synthetic 14
python main.py test system_prompts synthetic 13
python main.py test system_prompts synthetic 12
python main.py test system_prompts synthetic 11
python main.py test system_prompts synthetic 10
python main.py test system_prompts synthetic 9
python main.py test system_prompts synthetic 8
python main.py test system_prompts synthetic 7
python main.py test system_prompts synthetic 6
python main.py test system_prompts synthetic 5
python main.py test system_prompts synthetic 4
python main.py test system_prompts synthetic 3
python main.py test system_prompts synthetic 2
python main.py test system_prompts synthetic 1
python main.py test system_prompts real 16
python main.py test system_prompts real 15
python main.py test system_prompts real 14
python main.py test system_prompts real 13
python main.py test system_prompts real 12
python main.py test system_prompts real 11
python main.py test system_prompts real 10
python main.py test system_prompts real 9
python main.py test system_prompts real 8
python main.py test system_prompts real 7
python main.py test system_prompts real 6
python main.py test system_prompts real 5
python main.py test system_prompts real 4
python main.py test system_prompts real 3
python main.py test system_prompts real 2
python main.py test system_prompts real 1
python main.py test system_prompts awesome 16
python main.py test system_prompts awesome 15
python main.py test system_prompts awesome 14
python main.py test system_prompts awesome 13
python main.py test system_prompts awesome 12
python main.py test system_prompts awesome 11
python main.py test system_prompts awesome 10
python main.py test system_prompts awesome 9
python main.py test system_prompts awesome 8
python main.py test system_prompts awesome 7
python main.py test system_prompts awesome 6
python main.py test system_prompts awesome 5
python main.py test system_prompts awesome 4
python main.py test system_prompts awesome 3
python main.py test system_prompts awesome 2
python main.py test system_prompts awesome 1